POST http://localhost:3000/dogs
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyOTU0OTN9.0vxj6hHrFLT_3GsviTv19jY_MbsBbQsNhY01GFw3W2E
content-type: application/json

{
  "name": "Test",
  "age": 5, 
  "breed": "Test dog"
}

###
PATCH http://localhost:3000/dogs/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyOTU0OTN9.0vxj6hHrFLT_3GsviTv19jY_MbsBbQsNhY01GFw3W2E
content-type: application/json

{
  "user_id": 1
}

###
GET http://localhost:3000/dogs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyOTU0OTN9.0vxj6hHrFLT_3GsviTv19jY_MbsBbQsNhY01GFw3W2E

###
# signup
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Stassie",
  "email": "stassie@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
# login
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "stassie@gmail.com",
  "password": "password"
}