POST http://localhost:3000/dogs
content-type: application/json

{
  "name": "Princess",
  "age": 10, 
  "breed": "dalmation"
}

###
POST http://localhost:3000/users
content-type: application/json

{
  "name": "Stassie",
  "email": "stassie@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "stassie@gmail.com",
  "password": "password"
}